### ISSUE TITLE
How does this relate to revalidation?

### ISSUE THREAD

**Issue by bookercodes** [25th-floor/spected#3]
On the surface, it seems like [revalidation](https://github.com/25th-floor/revalidation) is a React-specific implementation of spected. 

Is the goal to make revalidation dependent on spected?

**Comment by busypeoples** [comment]
Exactly. Revalidation will have a dependency on Spected.
By decoupling this part we can an easily build an Inferno or Preact Form validation Component for example.

**Comment by bookercodes** [comment]
Awesome, that makes a lot of sense!

Can I use Revalidation or should I expect breaking changes?

**Comment by busypeoples** [comment]
There still might be some breaking changes up until the 1.0.0 release, but the Spected dependency will not break anything.

**Comment by bookercodes** [comment]
Awesome, good to know. I am building an admin dashboard for my work project, [pusher.com/sessions](pusher.com/sessions), and am considering Revalidation!
