### ISSUE TITLE
Documentation suggests I can do something I cannot

### ISSUE THREAD

**Issue by bookercodes** [25th-floor/spected#4]
The documentation says, 

> Calling `validate spected(validationRules, inputData)` should return

Which would suggest I can do something like this,

```js
const spected = require('spected')

const isGreaterThan = num => num > 5
const hasCapitalLetter = text => /[A-Z]/.test(text)

const validationRules = {
  name: [
    [ isGreaterThan(5),
      `Minimum Name length of 6 is required.`
    ],
  ],
  random: [
    [ isGreaterThan(7), 'Minimum Random length of 8 is required.' ],
    [ hasCapitalLetter, 'Random should contain at least one uppercase letter.' ],
  ]
}

const inputData = { name: 'abcdef', random: 'z'}


const res = spected(validationRules, inputData)

console.log(res)
```

However, `spected` is not a function

Just a little kink in the onboarding, which would be good to solve with better documentation!

**Comment by bookercodes** [comment]
Ah, I realise this is probably because I did `require('spected')` instead of `require(`spected`).default

**Comment by busypeoples** [comment]
Yes, `require('spected').default` should solve the problem. Let me know if there is still trouble.

**Comment by bookercodes** [comment]
Thanks @busypeoples! I am encountering an error, but I have created a separate issue for that (easier for newcomers to search)
