### ISSUE TITLE
Add support for validation of array of non-object values

### ISSUE THREAD

**Issue by jakubkoci** [25th-floor/spected#85]
At first, thanks for your good job with this library I really like it. 

I would like to be able to validate property which has array of strings for example.
```javascript
const input = {
  users: [
    'foobar', 
    'longerstring'
  ]
}

const validationRules = {
  users: [[ 
    array => array.every(item => item.length > 6), 
    'Every item in array must be string with at least 5 characters' 
  ]],
}

const validationResult = spected(validationRules, input)
```

And it would return this:
```javascript
{ users: true }
```
or this:
```javascript
{ users: [ 'Every item in array must be string with at least 5 characters' ] }
```
depending on validation predicate and input data.

Currently, it retuns error:
```javascript
TypeError: Invalid attempt to destructure non-iterable instance
```

I have tried to avoid validation of such property by omitting it from validation rules (that would be also nice to be able to do that, such as with other properties according to docs), but it also returns error:
```javascript
TypeError: Cannot read property '0' of undefined
```

**Comment by busypeoples** [comment]
I will have a look at the issue.

**Comment by busypeoples** [comment]
Yes, will add support for this use case in `0.5`

**Comment by busypeoples** [comment]
Updated to `0.5`, this should work now.
