### ISSUE TITLE
validations of missing field are skipped?

### ISSUE THREAD

**Issue by iwinux** [25th-floor/spected#91]
Hi,

As specified in the [unit test](https://github.com/25th-floor/spected/blob/master/test/index.js), validations of missing field are simply skipped - how should I ensure that every required fields are filled?

Thanks :)

**Comment by busypeoples** [comment]
Would be possible to define a default data object containing null for every key and then merging it with the provided data?

```js
const default = {id: null, name: null}
const providedData = {id: 1}
const data = merge(default, providedData)
```

**Comment by iwinux** [comment]
That looks good. Thanks!
