### ISSUE TITLE
Useless extra func call + curry for spected function

### ISSUE THREAD

**Issue by cloud-walker** [25th-floor/spected#92]
https://github.com/25th-floor/spected/blob/e7546e17ffb7ce58c06bceea11d5710c9dcb06ed/src/index.js#L70

I think you can just do
```javascript
export default validate(() => true, identity)
```
🎉

**Comment by busypeoples** [comment]
Very good. Do you want to do a Pull Request?

**Comment by busypeoples** [comment]
Excellent! Thanks. Will merge later on today.

**Comment by busypeoples** [comment]
Thanks @cloud-walker !
