### ISSUE TITLE
Update package?

### ISSUE THREAD

**Issue by willhoag** [25th-floor/spected#93]
Hi and thanks for the code. 👍 

Mind publishing the latest? Looking to utilize field names in messages.

Thanks!
![thank you](https://media1.giphy.com/media/3o7TKr0sYduhblYBgY/200w.gif)

**Comment by busypeoples** [comment]
Yes, will publish later today!

**Comment by willhoag** [comment]
Thank you. :)

**Comment by busypeoples** [comment]
Just released `0.6`.
